# Generated by Django 2.1.5 on 2020-09-14 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_id', models.IntegerField(default=0)),
                ('picture', models.ImageField(blank=True, upload_to='dog_images')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('DOB', models.DateField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DogBreed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='DogEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('date', models.DateField(max_length=128, null=True)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('dog', models.ManyToManyField(to='dog_aid.Dog')),
            ],
        ),
        migrations.CreateModel(
            name='DogEventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_event_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='DogOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_owner_id', models.IntegerField(default=0)),
                ('owner_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness_id', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('picture', models.ImageField(blank=True, upload_to='illness_images')),
                ('treatment', models.TextField(blank=True, max_length=1000)),
                ('call_vet', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('views', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog_aid.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('picture', models.ImageField(blank=True, upload_to='symptom_images')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('phone_number', models.IntegerField(default=0)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('dog_owner', models.ForeignKey(max_length=128, null=True, on_delete=django.db.models.deletion.CASCADE, to='dog_aid.DogOwner')),
            ],
        ),
        migrations.CreateModel(
            name='VetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vet_type_id', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='vet',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dog_aid.VetType'),
        ),
        migrations.AddField(
            model_name='illness',
            name='related_symptom',
            field=models.ManyToManyField(to='dog_aid.Symptom'),
        ),
        migrations.AddField(
            model_name='dogevent',
            name='event_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dog_aid.DogEventType'),
        ),
        migrations.AddField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(blank=True, max_length=128, on_delete=django.db.models.deletion.CASCADE, to='dog_aid.DogBreed'),
        ),
        migrations.AddField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(max_length=128, null=True, on_delete=django.db.models.deletion.CASCADE, to='dog_aid.DogOwner'),
        ),
    ]
