# Generated by Django 2.1.5 on 2020-07-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_aid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog', models.CharField(max_length=128, unique=True)),
                ('dob', models.IntegerField(default=0)),
                ('breed', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
