# Generated by Django 2.1.5 on 2020-09-16 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog_aid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogevent',
            name='dog',
        ),
        migrations.AddField(
            model_name='dogevent',
            name='dog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dog_aid.Dog'),
        ),
        migrations.AlterField(
            model_name='dogevent',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog_aid.DogEventType'),
        ),
    ]
