# Generated by Django 2.1.5 on 2020-07-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_aid', '0002_auto_20200718_1317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DogProfile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth',
            field=models.DateField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='breed',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dog',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
