# Generated by Django 2.1.5 on 2020-09-18 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog_aid', '0002_auto_20200916_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogowner',
            name='owner_name',
        ),
        migrations.AlterField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(max_length=128, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vet',
            name='dog_owner',
            field=models.ForeignKey(max_length=128, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DogOwner',
        ),
    ]
