# Generated by Django 2.1.5 on 2020-09-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_aid', '0003_auto_20200918_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='phone_number',
            field=models.CharField(max_length=500),
        ),
    ]
