# Generated by Django 2.1.5 on 2020-07-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog_aid', '0003_auto_20200718_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='dog',
            new_name='dog_name',
        ),
    ]
