# Generated by Django 2.1.5 on 2020-07-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_aid', '0005_auto_20200718_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_vet', models.CharField(blank=True, max_length=128)),
                ('phone_number', models.IntegerField(default=0)),
                ('address', models.CharField(blank=True, max_length=128)),
            ],
        ),
    ]
