# Generated by Django 2.1.5 on 2020-07-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_aid', '0006_vetprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vetprofile',
            old_name='address',
            new_name='county',
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='postcode',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='street',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='town',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
