# Generated by Django 2.1.5 on 2020-07-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_aid', '0007_auto_20200719_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('dog_name', models.CharField(blank=True, max_length=128)),
                ('date_of_birth', models.DateField(max_length=128, null=True)),
                ('breed_of_dog', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='breed_of_dog',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dog_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
    ]
