# Generated by Django 2.1.5 on 2020-07-25 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog_aid', '0008_auto_20200725_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogprofile',
            name='owner',
            field=models.ForeignKey(max_length=128, null=True, on_delete=django.db.models.deletion.CASCADE, to='dog_aid.UserProfile'),
        ),
    ]
