# Generated by Django 2.1.5 on 2020-07-27 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog_aid', '0011_auto_20200727_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog', models.CharField(blank=True, max_length=128)),
                ('vet', models.CharField(blank=True, max_length=128)),
                ('owner_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dog_aid.UserProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='owner',
            field=models.ForeignKey(max_length=128, null=True, on_delete=django.db.models.deletion.CASCADE, to='dog_aid.DogOwner'),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='dog_images'),
        ),
    ]
