# Generated by Django 2.1.5 on 2020-07-27 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog_aid', '0013_dogbreed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogprofile',
            name='dog_name',
            field=models.ForeignKey(blank=True, max_length=128, on_delete=django.db.models.deletion.CASCADE, to='dog_aid.DogOwner'),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='owner',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
