# Generated by Django 2.1.5 on 2020-07-27 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog_aid', '0014_auto_20200727_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogprofile',
            name='dog_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='owner',
            field=models.ForeignKey(max_length=128, null=True, on_delete=django.db.models.deletion.CASCADE, to='dog_aid.DogOwner'),
        ),
    ]
